### ISSUE TITLE
importing json_utils issues ImportError

### ISSUE THREAD

**Issue by lhonda** [martinkou/bson#19]
In [2]: from bson import json_util
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-3302acedf1cf> in <module>()
----> 1 from bson import json_util

/home/lhonda/.virtualenvs/test/local/lib/python2.7/site-packages/bson/json_util.py in <module>()
     84 
     85 import bson
---> 86 from bson import EPOCH_AWARE
     87 from bson.binary import Binary
     88 from bson.code import Code

ImportError: cannot import name EPOCH_AWARE

In [3]:

**Comment by wshayes** [comment]
Uninstall and reinstall:
pip uninstall bson
pip uninstall pymongo
pip install pymongo

The conflicting bson package overwrites the pymongo bson package.  Need to clean it and re-install pymongo.

**Comment by merwok** [comment]
That’s a different error that would need its own ticket to catch the attention of maintainers.

**Comment by Parkayun** [comment]
pybson has not json_util. You may confuse with mongo's bson. 
#41 will help you.

**Comment by onemadgeek** [comment]
If you're still getting this error:
uninstall pymongo and bson
install bson then pymongo

Anyone knows a better solution please add.
