### ISSUE TITLE
Inconsistent use of shebang

### ISSUE THREAD

**Issue by voodoonofx** [martinkou/bson#27]
Not sure if it's really an issue, but thought I'd bring up that several files in this package use an incosistent shebang line:

E.g.
`bson/__init__.py` uses `#!/usr/bin/python -OOOO`
`bson/codec.py` uses `#!/usr/bin/python -OOOO`
`bson/network.py` uses `#!/usr/bin/env python`

Perhaps all files should use the highly adaptable `#!/usr/bin/env python`? Is there some reason for this that's not immediately obvious to me?

**Comment by Parkayun** [comment]
good point.
I will use only `#!/usr/bin/env python`.
Thanks :)
