### ISSUE TITLE
This package has been removed from the pypi.

### ISSUE THREAD

**Issue by AiOO** [martinkou/bson#30]
https://pypi.python.org/pypi/bson :arrow_right: returns 404

**Comment by theonewolf** [comment]
Also hit this.  Wonder why?  Doesn't that have to be author-caused?  Or does PyPi automatically delete really old projects?

**Comment by AiOO** [comment]
I have no idea :(

**Comment by dubglan** [comment]
The same here. @martinkou, is this project no longer maintained? Should we fork it?

**Comment by crobinsonut** [comment]
Had this same problem. Google cached the page, and it looks like it was available ~48 hours ago.

@AiOO, @theonewolf , @dubglan: For a project I work on, we uploaded version 0.3.3 to http://openmdao.org/dists. There's an egg and a source distribution. Should be able to install with:

`easy_install -f http://openmdao.org/dists bson`.

It should work as a temporary measure until the PYPI issue gets resolved.

**Comment by sublee** [comment]
Why?

**Comment by Parkayun** [comment]
I uploaded to PyPI.
Now, We can use bson :)

**Comment by AiOO** [comment]
Thanks!
